### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Methers27** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#23]
Hi, trying to set up this integration for a soundbar that works with smart things, but keep returning this error in the log. I have installed the integration via HACS, and I have entered the following in my configuration.yaml (with the correct values for ID/api key)

media_player:
-  platform: smartthings_soundbar
   name: Soundbar
   api_key: ****
   device_id: ****
   max_volume: 30

The integration has never appeared in the UI, but if i go to info under configuration, I can see it as an active integration. This is the error I keep receiving:

Update for media_player.soundbar fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 34, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PiotrMachowski** [comment]
Can you try to run [this script](https://pastebin.com/H3tZxJMq)?

Do you have SmartThings integration set up?

**Comment by Methers27** [comment]
thanks for the quick reply, where should I be running the script? (sorry for the very basic question)

I don't have smartthings set up, should I have done this?

**Comment by PiotrMachowski** [comment]
You can run it anywhere you have installed python

You don't have to, but it would help with troubleshooting

**Comment by Methers27** [comment]
I got the below error running in pyscript:

Exception in </config/pyscript/smartthings.py> line 15: device = (await api.devices(device_ids=[DEVICE_ID]))[0] ^ TypeError: 'NoneType' object is not subscriptable

**Comment by Methers27** [comment]
I now get this error from the smartthings_soundbar script, it still does not appear in integrations

Update for media_player.soundbar fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 39, in device_update
    device_source = data['main']['inputSource']['value']
KeyError: 'inputSource'

**Comment by PiotrMachowski** [comment]
Something might be wrong with status of your device in SmartThings. What info do you get here? https://graph-eu01-euwest1.api.smartthings.com/device/list

**Comment by Methers27** [comment]
shows my device with status 'online'

**Comment by Methers27** [comment]
![Screenshot_20220130-183944_Chrome](https://user-images.githubusercontent.com/98242758/151712855-f4cbc474-82c2-46ea-a7cd-48e8445f5761.jpg)
