### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by yangtfu** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#27]
Logger: homeassistant.helpers.entity
Source: custom_components/smartthings_soundbar/api.py:35
Integration: smartthings_soundbar (documentation, issues)
First occurred: 12:32:56 (1 occurrences)
Last logged: 12:32:56

Update for media_player.soundbar fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 35, in device_update
    device_volume = data['main']['volume']['value']
KeyError: 'main'

**Comment by mimale** [comment]
Check your DEvice ID, to only use the XXX part of the URL and your Token
