### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mellowism** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#33]
Hi, I get an error in logs:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/smartthings_soundbar/api.py:35
Integration: smartthings_soundbar (documentation, issues)
First occurred: 19:21:56 (43 occurrences)
Last logged: 19:28:56

Update for media_player.stue_soundbar fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 35, in device_update
    device_volume = data['main']['volume']['value']
KeyError: 'main'
```
Config:
```
- platform: smartthings_soundbar
  name: Stue Soundbar
  api_key: "ladida etc"
  device_id: "xx:xx: etc"
```

**Comment by mimale** [comment]
I had similar issue. my problem was the Device ID was not correct. Check the DEvice ID (only use the xxx part, without the part before/) and check the Token
