### ISSUE TITLE
about device id web address

### ISSUE THREAD

**Issue by shawnzhou1120** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#35]
from ur instruction,the device ID is came from:  _graph-eu01-euwest1.api.smartthings.com/device_
https://graph-eu01-euwest1.api.smartthings.com/device/show/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX
but i found my decice ID is come from _graph-ap02-apnortheast2.api.smartthings.com/device/_
look like this:
https://graph-ap02-apnortheast2.api.smartthings.com/device/show/xxxx-xxx-xxx-xxx-xxxxx

the log in HA:
Update for media_player.soundbar fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 35, in device_update
    device_volume = data['main']['volume']['value']
KeyError: 'main'

**Comment by mimale** [comment]
only enter the part with xxxx-xxx-xxx-xxx-xxxxx as device ID

**Comment by shawnzhou1120** [comment]
but,looks,it is not work in my HA.

**Comment by mimale** [comment]
Did you enter the correct Token ID?

**Comment by niko-nylander** [comment]
I found device ID from here https://api.smartthings.com/v1/devices
