### ISSUE TITLE
Błąd  "list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by rafkan20** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#5]
Dzień dobry. Pisałem do Pana na telefonie w sprawie błędu który się pojawia w integracji SmartThings-Soundbar.
Poniżej wklejam to co pojawia się w Home Assistant:
```
Logger: homeassistant.helpers.entity
Source: custom_components/smartthings_soundbar/api.py:60
First occurred: 10:36:59 (344 occurrences)
Last logged: 11:34:10

Update for media_player.samsung_q70r fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 60, in device_update
    self._source_list = device_all_sources["value"]
TypeError: list indices must be integers or slices, not str 
```

**Comment by PiotrMachowski** [comment]
Problem powinien być rozwiązany
